//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Diagnostics;
using System.Text;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=4.0.30319.33440.
// 



public  class CurrentWeather
{
    private static Dictionary<string, PropertyDescriptor> properties;

    private static Dictionary<string, PropertyDescriptor> Properties
    {
        get
        {
            if(properties == null)
            {
                properties = new Dictionary<string, PropertyDescriptor>();
                foreach (PropertyDescriptor item in TypeDescriptor.GetProperties(typeof(CurrentWeather)))
                {
                    properties.Add(item.Name, item);
                }
            }
            return properties;
        }
    }

    string location;
    [XmlElement]
    public string Location
    {
        get { return location; }
        set { location = value; }
    }

    string time;
    [XmlElement]
    public string Time
    {
        get { return time; }
        set { time = value; }
    }
    string wind;
    [XmlElement]
    public string Wind
    {
        get { return wind; }
        set { wind = value; }
    }
    string visibility;
    [XmlElement]
    public string Visibility
    {
        get { return visibility; }
        set { visibility = value; }
    }
    string skyConditions;
    [XmlElement]
    public string SkyConditions
    {
        get { return skyConditions; }
        set { skyConditions = value; }
    }
    string temperature;
    [XmlElement]
    public string Temperature
    {
        get { return temperature; }
        set { temperature = value; }
    }
    string dewPoint;
    [XmlElement]
    public string DewPoint
    {
        get { return dewPoint; }
        set { dewPoint = value; }
    }
    string relativeHumidity;
    [XmlElement]
    public string RelativeHumidity
    {
        get { return relativeHumidity; }
        set { relativeHumidity = value; }
    }
    string pressure;
    [XmlElement]
    public string Pressure
    {
        get { return pressure; }
        set { pressure = value; }
    }
    string status;
    [XmlElement]
    public string Status
    {
        get { return status; }
        set { status = value; }
    }

    public override string ToString()
    {
        StringBuilder sb = new StringBuilder();
        foreach (string  key in Properties.Keys)
        {
            sb.AppendLine(string.Format("{0, -15}: {1}", key, Properties[key].GetValue(this)));
        }

        return sb.ToString();
    }


}